erda-project/telegraf

build.sh, conf/k8s/platform.alone.conf, conf/platform.alone.conf, conf/test.conf, config/config.go, entrypoint.sh, plugins/inputs/docker_summary/container_stats.go, plugins/inputs/docker_summary/container_stats_test.go, plugins/inputs/docker_summary/testdata/pod_info.json
=> some fix for build

plugins/inputs/dice_health/health.go, plugins/inputs/global/node/k8s.go, plugins/inputs/global/node/node.go, plugins/processors/add_kubernetes_metadata/add_kubernetes_metadata.go
resolves #
use otherlabels to store non dice label
=> labels fix

conf/k8s/platform.alone-mc.conf, conf/k8s/platform.alone.conf, conf/platform.alone.conf, conf/telegraf-app-edge.conf, conf/telegraf-app.conf, conf/telegraf-edge.conf, conf/telegraf.conf, plugins/inputs/all/all.go, plugins/inputs/selfstat/self.go
resolves #
self status /_api/health
=> telegraf selfstat

conf/k8s/platform.alone-mc.conf, conf/k8s/platform.alone.conf, conf/platform.alone.conf, conf/telegraf-app-edge.conf, conf/telegraf-app.conf, conf/telegraf-edge.conf, conf/telegraf.conf, plugins/inputs/all/all.go, plugins/inputs/selfstat/self.go
=> chery pick/telegraf selfstat

erda.yml
=> recover erda.yml

conf/k8s/telegraf.conf, plugins/processors/compatibility/compatibility.go
resolves #
- enable metadataserver
- recover deprecated
=> some fix for old code

conf/k8s/telegraf.conf, plugins/processors/compatibility/compatibility.go
=> cherry-pick

conf/k8s/telegraf-app-edge.conf, conf/k8s/telegraf-edge.conf, conf/k8s/telegraf.conf, entrypoint.sh, plugins/common/kubernetes/client.go, plugins/inputs/global/kubernetes/kubernetes.go, plugins/inputs/metaserver/metaserver.go
resolves #
k8s client fix for edge compute node,
campatibility some code
=> some fix for edge case

entrypoint.sh, erda.yml, plugins/inputs/metaserver/metaserver.go
=> fix for edge erda.yml

plugins/inputs/docker_summary/kubernentes.go, plugins/inputs/global/kubelet/kubelet.go
=> [cherry-pick]fix find

build.sh
=> Use standard image naming

erda.yml
=> Add udp protocol for telegraf-app

plugins/inputs/diskio/README.md, plugins/inputs/diskio/diskio.go, plugins/inputs/diskio/diskio_linux.go, plugins/inputs/diskio/diskio_linux_test.go, plugins/inputs/diskio/diskio_other.go, plugins/inputs/diskio/diskio_test.go
resolves https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=216833&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJSRU9QRU4iXSwiYXNzaWduZWVJRHMiOlsiMTAwMDMwMSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=-1&type=TASK
=> migrate from old diskio

conf/k8s/platform.alone-mc.conf
- platform cassandra metrics collect
- platform component monitor metrics collect
resolves #
=> add cassandra&monitor metrics

Dockerfile, conf/k8s/platform.alone-mc.conf
=> more performance metric

Dockerfile, conf/k8s/platform.alone-mc.conf
=> Cassandra metrics

plugins/processors/tag_override/tag_override.go
=> Add peer_address tag

conf/k8s/platform.alone-mc.conf, conf/telegraf-app.conf
=> config adjust

Dockerfile, conf/k8s/platform.alone-mc.conf, conf/telegraf-app.conf
=> Ratelimit config fix

conf/telegraf-app-edge.conf, conf/telegraf-app.conf
=> Update app metrics limit

conf/telegraf.conf
=> Diskio config fix

conf/k8s/platform.alone-mc.conf
=> add pipeline

plugins/inputs/kube_inventory/persistentvolumeclaim.go
=> segfault bug fix

plugins/inputs/kube_inventory/persistentvolumeclaim.go
=> Fix segfault official version

conf/telegraf-app-edge.conf, conf/telegraf-app.conf, erda.yml
=> Enable tcp metric input

conf/platform.alone.conf, conf/telegraf-app-edge.conf, conf/telegraf-app.conf, conf/telegraf-edge.conf, conf/telegraf.conf
=> Support spot output timeout config

erda.yml
=> Pprof default to disabled

conf/platform.alone.conf, conf/telegraf-app-edge.conf, conf/telegraf-app.conf, conf/telegraf-edge.conf, conf/telegraf.conf, erda.yml
=> remove useless

erda.yml
=> Fix erda.yml ports lost

conf/telegraf-app-edge.conf, conf/telegraf-app.conf
=> Use influx data_format for tcp input

plugins/processors/tag_override/tag_override.go
=> Add new span tag override rule

plugins/inputs/docker_summary/container_info.go
=> better error handle

plugins/inputs/addons/addons.go, plugins/inputs/global/kubernetes/pod.go
=> fix copy sync.map

pipeline.yml
=> support release/1.3 auto build

pipeline.yml
=> Unified product version management

plugins/processors/tag_override/tag_override.go
=> Fix db_system not add

.github/workflows/git-sync.yml, pipeline.yml
=> ci: add tag version & remove useless hack push

erda.yml
fix: replicas error when workflow is per node
@sixther-dc @erenming
=> fix: replicas error when workflow is per node

plugins/inputs/global/kubernetes/pod.go, plugins/inputs/global/node/k8s.go
=> fix invalid log

plugins/inputs/addons/addons.go
=> retrun in case error

erda.yml
=> add default env

plugins/inputs/addons/addons.go, plugins/inputs/addons/addons_v2.go
=> fix: watch exist and support redisfailover

.gitignore, conf/k8s/platform.alone-mc.conf
add kafka jmx metric tag
/assign @erenming
=> feat: add kafka metric tag

erda.yml, pipeline.yml
=> feat: update erda.yaml

Dockerfile, build.sh, pipeline.yml
=> feat: buildx

conf/telegraf-app.conf
add application_rpc rate limit default config
[erda issue](https://erda.cloud/erda/dop/projects/387/issues/all?id=566339&iterationID=12783&type=TASK)
resolves #
=> feat: add application_rpc rate limit default config
